/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'password' : Password,
  'email' : string,
  'luidId' : LuidId,
}
export type Category = string;
export type LuidId = string;
export type Password = string;
export interface Record {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'language' : string,
  'version' : string,
  'category' : Category,
  'price' : number,
  'fileUrl' : string,
}
export type ScriptId = bigint;
export interface UserProfile { 'email' : string, 'luidId' : LuidId }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScriptForSale' : ActorMethod<
    [string, string, Category, number, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteScript' : ActorMethod<[ScriptId], undefined>,
  'getAllScripts' : ActorMethod<[], Array<Record>>,
  'getAllUserAccounts' : ActorMethod<[], Array<Account>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPurchasedScripts' : ActorMethod<[LuidId], Array<ScriptId>>,
  'getScriptById' : ActorMethod<[ScriptId], Record>,
  'getScriptsByCategory' : ActorMethod<[Category], Array<Record>>,
  'getScriptsByLanguage' : ActorMethod<[string], Array<Record>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasPurchasedScript' : ActorMethod<[LuidId, ScriptId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[LuidId], boolean>,
  'login' : ActorMethod<[LuidId, string], boolean>,
  'purchaseScript' : ActorMethod<[LuidId, ScriptId], undefined>,
  'register' : ActorMethod<[LuidId, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateScript' : ActorMethod<
    [ScriptId, string, string, Category, number, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];