/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScriptId = IDL.Nat;
export const Record = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'language' : IDL.Text,
  'version' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
  'fileUrl' : IDL.Text,
});
export const Password = IDL.Text;
export const LuidId = IDL.Text;
export const Account = IDL.Record({
  'password' : Password,
  'email' : IDL.Text,
  'luidId' : LuidId,
});
export const UserProfile = IDL.Record({
  'email' : IDL.Text,
  'luidId' : LuidId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScriptForSale' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteScript' : IDL.Func([ScriptId], [], []),
  'deleteUser' : IDL.Func([LuidId], [], []),
  'updateUser' : IDL.Func([LuidId, IDL.Text, IDL.Text], [], []),
  'getAllScripts' : IDL.Func([], [IDL.Vec(Record)], ['query']),
  'getAllUserAccounts' : IDL.Func([], [IDL.Vec(Account)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPurchasedScripts' : IDL.Func([LuidId], [IDL.Vec(ScriptId)], ['query']),
  'getScriptById' : IDL.Func([ScriptId], [Record], ['query']),
  'getScriptsByCategory' : IDL.Func([Category], [IDL.Vec(Record)], ['query']),
  'getScriptsByLanguage' : IDL.Func([IDL.Text], [IDL.Vec(Record)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasPurchasedScript' : IDL.Func([LuidId, ScriptId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([LuidId], [IDL.Bool], ['query']),
  'login' : IDL.Func([LuidId, IDL.Text], [IDL.Bool], []),
  'purchaseScript' : IDL.Func([LuidId, ScriptId], [], []),
  'register' : IDL.Func([LuidId, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateScript' : IDL.Func(
      [
        ScriptId,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScriptId = IDL.Nat;
  const Record = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'language' : IDL.Text,
    'version' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
    'fileUrl' : IDL.Text,
  });
  const Password = IDL.Text;
  const LuidId = IDL.Text;
  const Account = IDL.Record({
    'password' : Password,
    'email' : IDL.Text,
    'luidId' : LuidId,
  });
  const UserProfile = IDL.Record({ 'email' : IDL.Text, 'luidId' : LuidId });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScriptForSale' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteScript' : IDL.Func([ScriptId], [], []),
    'deleteUser' : IDL.Func([LuidId], [], []),
    'updateUser' : IDL.Func([LuidId, IDL.Text, IDL.Text], [], []),
    'getAllScripts' : IDL.Func([], [IDL.Vec(Record)], ['query']),
    'getAllUserAccounts' : IDL.Func([], [IDL.Vec(Account)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPurchasedScripts' : IDL.Func([LuidId], [IDL.Vec(ScriptId)], ['query']),
    'getScriptById' : IDL.Func([ScriptId], [Record], ['query']),
    'getScriptsByCategory' : IDL.Func([Category], [IDL.Vec(Record)], ['query']),
    'getScriptsByLanguage' : IDL.Func([IDL.Text], [IDL.Vec(Record)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasPurchasedScript' : IDL.Func([LuidId, ScriptId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([LuidId], [IDL.Bool], ['query']),
    'login' : IDL.Func([LuidId, IDL.Text], [IDL.Bool], []),
    'purchaseScript' : IDL.Func([LuidId, ScriptId], [], []),
    'register' : IDL.Func([LuidId, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateScript' : IDL.Func(
        [
          ScriptId,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
